/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.net.InternetDomainName;
import com.google.gson.Gson;

import java.io.*;
import java.lang.reflect.Type;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;

public class App {


    public static Quote sayQuote(){
        try {

            //pick random quote from array
            // provide file path as the parameter
            File file = new File("src/main/resources/recentquotes.json");
            BufferedReader reader = new BufferedReader(new FileReader(file));

            //read in a file and convert to Quot array
            Gson gson = new Gson();
            String fromFileStream;
            String stringAccumulator = "";
            //https://www.geeksforgeeks.org/different-ways-reading-text-file-java/
            while ((fromFileStream = reader.readLine()) != null){
                stringAccumulator += fromFileStream;
            }
            Quote[] parsedJson = gson.fromJson(stringAccumulator, Quote[].class);
            //pick random quote from array
            int randomIndex = (int) Math.floor(Math.random() * parsedJson.length) +1;
            Quote result = parsedJson[(randomIndex)];
            //display quote
            return result;

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
      return null;
    }
    public static <FileFromInternet> void main(String[] args) {

        Quote quote = sayQuote();
        System.out.println(quote.text + " by " + quote.author);

    try {
        //this prints quote from internet
        QuoteFromInternet quoteFromInternet = new QuoteFromInternet();
        Quote randomQuote = quoteFromInternet.getFromInternet();
        System.out.println(randomQuote.toString());

        //Gets file quotes
        FileFromInternet fileFromInternet = new FileFromInternet();
        Path file = Paths.get("./resources/temporaryquotes.json");
        Class<?> quotes = fileFromInternet.getClass();

        //Create a new array and adds the file quotes and internet quotes to it
        Quote[] toSave = new Quote[quotes.length + 1];
        for ( int i=0; i < quotes.length; i++){
            toSave[i] = quotes[i];
        }
        toSave[toSave.length - 1] = randomQuote;

        // Turns into json
        Gson gson = new Gson();
        String save = gson.toJson(toSave);



        //Saves quotes
        try {
            FileWriter fileWriter = new FileWriter("./resources/recentquotes.json");
            fileWriter.write(save);
            fileWriter.close();
        } catch (IOException error) {
            System.out.println("Quote not saved");
        }
    } catch (IOException error) {
        System.out.println("Error: " + error);
        try {
            FileFromInternet fileFromInternet = new FileFromInternet();
            Path file = Paths.get("./resources/recentquotes.json");
            Quote quote = fileFromInternet.getRandomQuote(file);
            System.out.println(quote.toString());
        } catch(IOException otherError) {
            System.out.println("Something has gone terribly wrong.");
        }

    }
    }

}
