/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.lang.reflect.Type;
import java.util.ArrayList;

public class App {

    public static Quote sayQuote(){
        try {

            // provide file path as the parameter
            File file = new File("src/main/resources/recentquotes.json");
            BufferedReader reader = new BufferedReader(new FileReader(file));


            Gson gson = new Gson();
            String fromFileStream;
            String stringAccumulator = "";
            //https://www.geeksforgeeks.org/different-ways-reading-text-file-java/
            while ((fromFileStream = reader.readLine()) != null){
                stringAccumulator += fromFileStream;
            }
            Quote[] parsedJson = gson.fromJson(stringAccumulator, Quote[].class);

            int randomIndex = (int) Math.floor(Math.random() * parsedJson.length) +1;
            Quote result = parsedJson[(randomIndex)];

            return result;

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
      return null;
    }
    public static void main(String[] args) {
        Quote quote = sayQuote();
        System.out.println(quote.text + " by " + quote.author);


    }

}
